#!/bin/bash
#
#$ -cwd
#$ -j y
#
#$  -S /bin/bash
perl exp_H3K27ac_gene_split_200.nor.pl /NAS4/lien/Chia-pet_B73_AGPV4/identify_enhancer_and_promoter_without_IgG/use_chip_identify_enhancer/ear_candidate_active_enhancer_with_H3K27ac_final_no_H3K4me3_v.bed /NAS4/lien/chip_seq/call_peak_add_CK/merge_repeats_and_generate_wig/call_peak_without_CK/Ear_H3K27ac_rep3_map2AGPv4_peak_p5_MACS_wiggle/treat/Ear_H3K27ac_rep3_map2AGPv4_peak_p5_treat_afterfiting.pileup 20 H3K27ac_profile_for_ear_typical_enhancer.txt
perl exp_H3K27ac_gene_split_200.nor.pl /NAS4/lien/Chia-pet_B73_AGPV4/identify_enhancer_and_promoter_without_IgG/use_chip_identify_enhancer/Sd_candidate_active_enhancer_with_H3K27ac_final_no_H3K4me3_v.bed /NAS4/lien/chip_seq/call_peak_add_CK/merge_repeats_and_generate_wig/call_peak_without_CK/Sd_H3K27ac_rep3_map2AGPv4_peak_p5_MACS_wiggle/treat/Sd_H3K27ac_rep3_map2AGPv4_peak_p5_treat_afterfiting.pileup 20 H3K27ac_profile_for_seedling_typical_enhancer.txt
perl exp_H3K27ac_gene_split_200.nor.pl ../ear_super_peaks_without_CK /NAS4/lien/chip_seq/call_peak_add_CK/merge_repeats_and_generate_wig/call_peak_without_CK/Ear_H3K27ac_rep3_map2AGPv4_peak_p5_MACS_wiggle/treat/Ear_H3K27ac_rep3_map2AGPv4_peak_p5_treat_afterfiting.pileup 200 H3K27ac_profile_for_ear_super_enhancer.txt
perl exp_H3K27ac_gene_split_200.nor.pl ../seedling_super_peaks_without_CK /NAS4/lien/chip_seq/call_peak_add_CK/merge_repeats_and_generate_wig/call_peak_without_CK/Sd_H3K27ac_rep3_map2AGPv4_peak_p5_MACS_wiggle/treat/Sd_H3K27ac_rep3_map2AGPv4_peak_p5_treat_afterfiting.pileup 200 H3K27ac_profile_for_seedling_super_enhancer.txt
